/mob/living/simple_animal/hostile/blackmesa/xen/bullsquid
	name = "bullsquid"
	desc = "Противное инопланетное существо прямиком из другого измерения. Его противные глаза уже сверлят вас."
	icon = 'modular_bluemoon/olgachan/blackmesafromnova/icons/mobs.dmi'
	icon_state = "bullsquid"
	icon_living = "bullsquid"
	icon_dead = "bullsquid_dead"
	icon_gib = null
	mob_biotypes = list(MOB_ORGANIC, MOB_BEAST)
	environment_smash = ENVIRONMENT_SMASH_STRUCTURES
	faction = list(FACTION_XEN)
	speak_chance = 50
	speak_emote = list("growls")
	emote_taunt = list("growls", "snarls", "grumbles")
	taunt_chance = 100
	turns_per_move = 7
	maxHealth = 110
	health = 110
	obj_damage = 50
	harm_intent_damage = 15
	melee_damage_lower = 15
	melee_damage_upper = 15
	ranged = TRUE
	retreat_distance = 4
	minimum_distance = 4
	dodging = TRUE
	projectilesound = 'modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/bullsquid/goo_attack3.ogg'
	melee_damage_upper = 18
	attack_sound = 'modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/bullsquid/attack1.ogg'
	gold_core_spawnable = HOSTILE_SPAWN
	alert_sounds = list('modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/bullsquid/detect1.ogg','modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/bullsquid/detect2.ogg','modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/bullsquid/detect3.ogg')
	projectiletype = /obj/item/projectile/neurotox
