/mob/living/simple_animal/hostile/blackmesa/xen/gonome
	name = "Gonome"
	desc = "Довольно опасная мутация обычного зомби! Вам точно стоило тратить время на его рассмотрение?"
	icon = 'modular_bluemoon/olgachan/blackmesafromnova/icons/mobs.dmi'
	icon_state = "gonome"
	icon_living = "gonome"
	icon_dead = "gonome_dead"
	icon_gib = "syndicate_gib"
	mob_biotypes = MOB_ORGANIC|MOB_HUMANOID
	environment_smash = ENVIRONMENT_SMASH_STRUCTURES
	faction = list(FACTION_XEN)
	speak_chance = 50
	speak_emote = list("Рычит")
	speed = 1
	emote_taunt = list("Рычит", "Орёт", "Кряхтит")
	taunt_chance = 100
	turns_per_move = 40
	projectiletype = /obj/item/projectile/neurotox
	maxHealth = 3000
	health = 3000
	stat_attack = UNCONSCIOUS
	obj_damage = 70
	harm_intent_damage = 25
	melee_damage_lower = 30
	melee_damage_upper = 30
	attack_sound = 'modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/bullsquid/attack1.ogg'
	gold_core_spawnable = HOSTILE_SPAWN
	minbodytemp = 0
	maxbodytemp = 1500
	alert_sounds = list ('modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/gonome/gonomealert1.ogg','modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/gonome/gonomealert3.ogg','modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/gonome/gonomealert2.ogg','modular_bluemoon/olgachan/blackmesafromnova/sound/mobs/gonome/gonomealert4.ogg')
	loot = list(/obj/effect/gibspawner/human, /obj/item/wrench/shepard)
